[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range"


[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"




